
CREATE OR ALTER VIEW vw_All_Plants_Data AS

 SELECT 'EG1_16' AS  plantname,  * FROM EG1_16
UNION ALL
 SELECT 'EG1_21' AS  plantname,  * FROM EG1_21
UNION ALL
 SELECT 'EG1_23' AS  plantname,  * FROM EG1_23
UNION ALL
 SELECT 'EG1_25' AS  plantname,  * FROM EG1_25
UNION ALL
 SELECT 'EG2_17' AS  plantname,  * FROM EG2_17
UNION ALL
 SELECT 'EG2_22' AS  plantname,  * FROM EG2_22
UNION ALL
 SELECT 'Fort_16' AS  plantname,  * FROM Fort_16
UNION ALL
 SELECT 'Fort_21' AS  plantname,  * FROM Fort_21
UNION ALL
 SELECT 'FPC_18' AS  plantname,  * FROM FPC_18
UNION ALL
 SELECT 'FPC_23' AS  plantname,  * FROM FPC_23
UNION ALL
 SELECT 'KOLN_21' AS  plantname,  * FROM KOLN_21
UNION ALL
 SELECT 'KOLN_24' AS  plantname,  * FROM KOLN_24
UNION ALL
 SELECT 'Koln_MR3050' AS  plantname,  * FROM Koln_MR3050
UNION ALL
 SELECT 'KOLN_R200A' AS  plantname,  * FROM KOLN_R200A
UNION ALL
 SELECT 'KOLN_R200D' AS  plantname,  * FROM KOLN_R200D
UNION ALL
 SELECT 'LAO_15' AS  plantname,  * FROM LAO_15
UNION ALL
 SELECT 'LAO_17' AS  plantname,  * FROM LAO_17
UNION ALL
 SELECT 'LAO_20' AS  plantname,  * FROM LAO_20
UNION ALL
 SELECT 'LAO_23' AS  plantname,  * FROM LAO_23
UNION ALL
 SELECT 'LAO_24' AS  plantname,  * FROM LAO_24
UNION ALL
 SELECT 'NanYa1_23' AS  plantname,  * FROM NanYa1_23
UNION ALL
 SELECT 'NanYa3_21' AS  plantname,  * FROM NanYa3_21
UNION ALL
 SELECT 'NorthChem_21' AS  plantname,  * FROM NorthChem_21
UNION ALL
 SELECT 'OC_19' AS  plantname,  * FROM OC_19
UNION ALL
 SELECT 'OC_25' AS  plantname,  * FROM OC_25
UNION ALL
 SELECT 'ORL_23' AS  plantname,  * FROM ORL_23
UNION ALL
 SELECT 'OUCC_24' AS  plantname,  * FROM OUCC_24
UNION ALL
 SELECT 'P1_20' AS  plantname,  * FROM P1_20
UNION ALL
 SELECT 'P1_23' AS  plantname,  * FROM P1_23
UNION ALL
 SELECT 'P2_20' AS  plantname,  * FROM P2_20
UNION ALL
 SELECT 'P2_24' AS  plantname,  * FROM P2_24
UNION ALL
 SELECT 'PCG_15' AS  plantname,  * FROM PCG_15
UNION ALL
 SELECT 'PCG_17' AS  plantname,  * FROM PCG_17
UNION ALL
 SELECT 'PCG_19' AS  plantname,  * FROM PCG_19
UNION ALL
 SELECT 'PCG_22' AS  plantname,  * FROM PCG_22
UNION ALL
 SELECT 'RILDMD_19' AS  plantname,  * FROM RILDMD_19
UNION ALL
 SELECT 'RILDMD_22' AS  plantname,  * FROM RILDMD_22
UNION ALL
 SELECT 'RILDMD_25' AS  plantname,  * FROM RILDMD_25
UNION ALL
 SELECT 'RILHMD1_25' AS  plantname,  * FROM RILHMD1_25
UNION ALL
 SELECT 'RILHMD2_24' AS  plantname,  * FROM RILHMD2_24
UNION ALL
 SELECT 'RILHMD3_24' AS  plantname,  * FROM RILHMD3_24
UNION ALL
 SELECT 'RILJ3_19' AS  plantname,  * FROM RILJ3_19
UNION ALL
 SELECT 'RILVMD_23' AS  plantname,  * FROM RILVMD_23
UNION ALL
 SELECT 'Sadara_19' AS  plantname,  * FROM Sadara_19
UNION ALL
 SELECT 'Sadara_22' AS  plantname,  * FROM Sadara_22
UNION ALL
 SELECT 'Sasol' AS  plantname,  * FROM Sasol
UNION ALL
 SELECT 'Sasol_24' AS  plantname,  * FROM Sasol_24
UNION ALL
 SELECT 'SCO_13' AS  plantname,  * FROM SCO_13
UNION ALL
 SELECT 'SCO_15' AS  plantname,  * FROM SCO_15
UNION ALL
 SELECT 'SCO_18' AS  plantname,  * FROM SCO_18
UNION ALL
 SELECT 'SCO_21' AS  plantname,  * FROM SCO_21
UNION ALL
 SELECT 'SCO_24' AS  plantname,  * FROM SCO_24
UNION ALL
 SELECT 'SJ2_24' AS  plantname,  * FROM SJ2_24
UNION ALL
 SELECT 'SJ3_25' AS  plantname,  * FROM SJ3_25
UNION ALL
 SELECT 'SJ4_23' AS  plantname,  * FROM SJ4_23
UNION ALL
 SELECT 'SJ5_23' AS  plantname,  * FROM SJ5_23
UNION ALL
 SELECT 'SJ7_25' AS  plantname,  * FROM SJ7_25
UNION ALL
 SELECT 'SSTPC_18' AS  plantname,  * FROM SSTPC_18
UNION ALL
 SELECT 'SSTPC_20' AS  plantname,  * FROM SSTPC_20
UNION ALL
 SELECT 'TNZFB_16' AS  plantname,  * FROM TNZFB_16
UNION ALL
 SELECT 'TNZFB_18' AS  plantname,  * FROM TNZFB_18
UNION ALL
 SELECT 'TNZR1_18' AS  plantname,  * FROM TNZR1_18
UNION ALL
 SELECT 'TNZR1_22' AS  plantname,  * FROM TNZR1_22
UNION ALL
 SELECT 'TNZR1_25' AS  plantname,  * FROM TNZR1_25
UNION ALL
 SELECT 'TNZR2_18' AS  plantname,  * FROM TNZR2_18
UNION ALL
 SELECT 'TNZR2_22' AS  plantname,  * FROM TNZR2_22
UNION ALL
 SELECT 'TNZR2_25' AS  plantname,  * FROM TNZR2_25
UNION ALL
 SELECT 'TNZR4_18' AS  plantname,  * FROM TNZR4_18
UNION ALL
 SELECT 'TNZR4_22' AS  plantname,  * FROM TNZR4_22
UNION ALL
 SELECT 'ZPC1_23' AS  plantname,  * FROM ZPC1_23
UNION ALL
 SELECT 'ZPC2_25' AS  plantname,  * FROM ZPC2_25
UNION ALL
 SELECT 'ZRCC_18' AS  plantname,  * FROM ZRCC_18
UNION ALL
 SELECT 'ZRCC_23' AS  plantname,  * FROM ZRCC_23

